[package]
name = "snowflake-uid"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
chrono = { version = "0.4", features = ["now"], default-features = false}

[dev-dependencies]
criterion = "0.7"
